services:
  golangApp:
    build: ./
    image: golangs
    ports:
      - "80:8080"
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      
